# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: python:2-alpine
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout
      - run: 
          name: Build stage
          command: |
            python -m py_compile sources/add2vals.py sources/calc.py
            
  test:
    docker:
      - image: qnib/pytest
      
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py
      - store_test_results:
          path: test-reports
          
workflows:
  version: 2
  full_workflow:
    jobs:
      - build
      - test: 
          requires:
            - build